package com.mycompany.practica5;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;

/**
 *
 * @author Víctor y Xavi
 */
public class Practica5 extends javax.swing.JFrame {
    boolean c_red = true; 
    boolean c_green = true;
    boolean c_blue = true;
    JOptionPane optionPane = new JOptionPane("Tiene que dejar un color mínimo",JOptionPane.WARNING_MESSAGE);
    JDialog dialog = optionPane.createDialog("Warning!");


    public Practica5() {
        initComponents();
        cbTodos.setSelected(true);
        cbRojo.setSelected(true);
        cbVerde.setSelected(true);
        cbAzul.setSelected(true);
        rbsupder.setSelected(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoMarca = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cbTodos = new javax.swing.JCheckBox();
        cbRojo = new javax.swing.JCheckBox();
        cbVerde = new javax.swing.JCheckBox();
        cbAzul = new javax.swing.JCheckBox();
        Etiqueta1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rbsupizq = new javax.swing.JRadioButton();
        rbinfizq = new javax.swing.JRadioButton();
        rbsupder = new javax.swing.JRadioButton();
        rbinfder = new javax.swing.JRadioButton();
        Etiqueta2 = new javax.swing.JLabel();
        lienzo1 = new com.mycompany.practica5.Lienzo();
        bexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbTodos.setText("Todos");
        cbTodos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbTodosStateChanged(evt);
            }
        });

        cbRojo.setForeground(new java.awt.Color(255, 0, 0));
        cbRojo.setText("Rojo");
        cbRojo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbRojoStateChanged(evt);
            }
        });

        cbVerde.setForeground(new java.awt.Color(0, 204, 51));
        cbVerde.setText("Verde");
        cbVerde.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbVerdeStateChanged(evt);
            }
        });

        cbAzul.setForeground(new java.awt.Color(51, 51, 255));
        cbAzul.setText("Azul");
        cbAzul.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbAzulStateChanged(evt);
            }
        });

        Etiqueta1.setText("Selecciona color Imagen:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Etiqueta1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbAzul, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbRojo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbVerde, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbTodos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Etiqueta1)
                .addGap(19, 19, 19)
                .addComponent(cbTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbVerde)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbRojo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        grupoMarca.add(rbsupizq);
        rbsupizq.setText("Superior izquierda");
        rbsupizq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbsupizqActionPerformed(evt);
            }
        });

        grupoMarca.add(rbinfizq);
        rbinfizq.setText("Inferior izquierda");
        rbinfizq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbinfizqActionPerformed(evt);
            }
        });

        grupoMarca.add(rbsupder);
        rbsupder.setText("Superior derecha");
        rbsupder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbsupderActionPerformed(evt);
            }
        });

        grupoMarca.add(rbinfder);
        rbinfder.setText("Inferior derecha");
        rbinfder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbinfderActionPerformed(evt);
            }
        });

        Etiqueta2.setText("Selecciona posición logo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbsupizq)
                    .addComponent(rbinfizq)
                    .addComponent(rbsupder)
                    .addComponent(rbinfder)
                    .addComponent(Etiqueta2))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Etiqueta2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbsupizq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbinfizq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbsupder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbinfder)
                .addContainerGap())
        );

        javax.swing.GroupLayout lienzo1Layout = new javax.swing.GroupLayout(lienzo1);
        lienzo1.setLayout(lienzo1Layout);
        lienzo1Layout.setHorizontalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );
        lienzo1Layout.setVerticalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );

        bexit.setBackground(new java.awt.Color(0, 0, 0));
        bexit.setForeground(new java.awt.Color(255, 255, 255));
        bexit.setText("Salir");
        bexit.setBorder(null);
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lienzo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(bexit, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(182, 182, 182))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(bexit, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lienzo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void cbTodosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbTodosStateChanged
           if(cbTodos.isSelected() == true){
            cbRojo.setSelected(true);
            cbVerde.setSelected(true);
            cbAzul.setSelected(true);
            
            c_red= true;
            c_green= true;
            c_blue= true;
            
            lienzo1.cambioColor(c_red, c_green, c_blue);
        }else{
            if(cbAzul.isSelected()== true & cbVerde.isSelected()== true & cbRojo.isSelected()== true){
                cbTodos.setSelected(true);
              
            }
        }
    }//GEN-LAST:event_cbTodosStateChanged

    private void cbRojoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbRojoStateChanged
           if (cbRojo.isSelected() == false){
            cbTodos.setSelected(false);
           
            if(cbAzul.isSelected()== false & cbVerde.isSelected()== false ){
                cbRojo.setSelected(true);
                dialog.setVisible(true);
            }
            c_red = false;
        }else{
            c_red= true;
            if(cbAzul.isSelected()== true & cbVerde.isSelected()== true){
                cbTodos.setSelected(true);
            }
         
        }
        lienzo1.cambioColor(c_red, c_green, c_blue);
        
    }//GEN-LAST:event_cbRojoStateChanged

    private void cbVerdeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbVerdeStateChanged
         if (cbVerde.isSelected() == false){
            cbTodos.setSelected(false);
           
            if(cbAzul.isSelected()== false & cbRojo.isSelected()== false ){
                cbVerde.setSelected(true);
                dialog.setVisible(true);
            }
            c_green = false;
        }else{
            c_green= true;
            if(cbAzul.isSelected()== true & cbRojo.isSelected()== true){
                cbTodos.setSelected(true);
            }
            
        }
        lienzo1.cambioColor(c_red, c_green, c_blue);
    }//GEN-LAST:event_cbVerdeStateChanged

    private void cbAzulStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbAzulStateChanged
        if (cbAzul.isSelected() == false){
            cbTodos.setSelected(false);
           
            if(cbRojo.isSelected()== false & cbVerde.isSelected()== false ){
                cbAzul.setSelected(true);
                dialog.setVisible(true);
            }
            c_blue = false;
        }else{
            c_blue= true;
            if(cbRojo.isSelected()== true & cbVerde.isSelected()== true){
                cbTodos.setSelected(true);
            }
            
        }
        lienzo1.cambioColor(c_red, c_green, c_blue);
    }//GEN-LAST:event_cbAzulStateChanged

    private void rbsupizqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbsupizqActionPerformed
        if(rbsupizq.isSelected() == true){
            lienzo1.dibujarLogo(0, 0);
        }
    }//GEN-LAST:event_rbsupizqActionPerformed

    private void rbinfizqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbinfizqActionPerformed
        if(rbinfizq.isSelected() == true){
            lienzo1.dibujarLogo(0, 325);
        }
    }//GEN-LAST:event_rbinfizqActionPerformed

    private void rbsupderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbsupderActionPerformed
        if(rbsupder.isSelected() == true){
            lienzo1.dibujarLogo(477, 0);
        }
    }//GEN-LAST:event_rbsupderActionPerformed

    private void rbinfderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbinfderActionPerformed
         if(rbinfder.isSelected() == true){
            lienzo1.dibujarLogo(477, 325);
        }
    }//GEN-LAST:event_rbinfderActionPerformed

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bexitActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practica5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practica5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practica5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practica5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practica5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Etiqueta1;
    private javax.swing.JLabel Etiqueta2;
    private javax.swing.JButton bexit;
    private javax.swing.JCheckBox cbAzul;
    private javax.swing.JCheckBox cbRojo;
    private javax.swing.JCheckBox cbTodos;
    private javax.swing.JCheckBox cbVerde;
    private javax.swing.ButtonGroup grupoMarca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.mycompany.practica5.Lienzo lienzo1;
    private javax.swing.JRadioButton rbinfder;
    private javax.swing.JRadioButton rbinfizq;
    private javax.swing.JRadioButton rbsupder;
    private javax.swing.JRadioButton rbsupizq;
    // End of variables declaration//GEN-END:variables
}
